apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 3009
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3009"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: billing-db
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: billing-db
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: billing-db
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-db
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: billing-db
                  key: name
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: billing-rabbitmq
                  key: url
            - name: CORS_ORIGIN
              value: "https://steep-geology-napping.ngrok-free.dev"
            - name: ORG_SERVICE_URL
              value: "http://organization-service:3002"
            - name: CUSTOMER_SERVICE_URL
              value: "http://customer-service-node:3004"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service-node:3006"
            - name: TAX_SERVICE_URL
              value: "http://tax-service:3005"
            - name: DOCUMENT_SERVICE_URL
              value: "http://document-service:3003"
            - name: INTERNAL_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: internal-service-secret
                  key: value
